### ISSUE TITLE
Cannot get the Artifact files  built on the before step 

### ISSUE THREAD

**Issue by liuzel01** [danharrin/monorepo-split-github-action#54]
this is content of my packages-release.yml: 

but when the Actions done, the split repo  https://github.com/example/administration.git does not have the src/Administration/Resources/public 

so how can i get the new generated directory or files be splitted to the new repo ？

best regards. 

<img width="578" alt="image" src="https://github.com/danharrin/monorepo-split-github-action/assets/26734740/ceb0b9c4-41d6-4231-99c4-35e035b658a9">

```yaml
name: 'Packages Release'
on:
  push:
    branches:
      - 'trunk'
    paths:
      - src/Administration/**/*
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
jobs:
  jobs-split: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          -
            local_path: 'Administration'
            split_repository: 'administration'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Administration 
        run: |
          cd src/Administration/Resources
          mkdir -p public/static
          echo ${{ github.sha }} > public/static/Release.txt
      - name: Test Administration
        run: |
          ls -lht src/Administration/Resources/public 
      - name: Split Monorepo Without Tag 
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          package_directory: 'src/Administration'
          repository_organization: 'example'
          repository_name: '${{ matrix.package.split_repository }}'
          branch: 'trunk'
          user_name: "example"
          user_email: "example@gmail.com"
```
